RECT_SHRINK_THRESHOLD: 0.1

CUT_RATE_MAX: 0.007
CUT_RATE_MAX_2: 0.005
CUT_RATE_MIN: 0.01

THRESH_MIN_POINTS_AFTER_DELETING: 10
DELETE_TIMES_EVERY_EPOCH: 2

FINAL_POINT_FLIP_THRESH: -0.0001
ANCHOR_FIT_DEGREE_THRESH: 10

HEIGHT_LENGTH_RATE: 0.3969212090597959
HEIGHT_WIDTH_RATE: 0.9305644265920366
    
KEY_VERTEX_MOVE_DIST_THRESH: 0.001
MIN_HEIGHT_NORMAL: 1
MAX_HEIGHT_NORMAL: 2
MAX_TOP_TRUNCATE: 5
MIN_TOP_TRUNCATE: 0
MAX_BOT_TRUNCATE: 5
MIN_BOT_TRUNCATE: -5
    
MIN_LENGTH: 3.0
MAX_LENGTH: 5.0
MIN_WIDTH: 1.2
MAX_WIDTH: 2.2
    
LENGTH_WIDTH_BOUNDARY: 2.2

THRESH_RANSAC: 0.15
THRESH_SEG_MAX: 7
REGION_GROWTH_RATIO: 0.8